package MantisBT;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateFilter1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createFilter1() throws InterruptedException {
    driver.get("http://localhost:8989/login_page.php");
    driver.manage().window().setSize(new Dimension(766, 640));
    driver.findElement(By.id("username")).sendKeys("administrator");
    driver.findElement(By.cssSelector(".width-40")).click();
    driver.findElement(By.id("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".width-40")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("menu-toggler")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("li:nth-child(2) .menu-text")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".widget-main:nth-child(1) > .table-responsive"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".widget-main:nth-child(1) > .table-responsive"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".widget-main:nth-child(1) > .table-responsive"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("view_state_filter")).click();
    {
      WebElement element = driver.findElement(By.id("view_state_filter"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("view_state")).click();
    {
      WebElement dropdown = driver.findElement(By.name("view_state"));
      dropdown.findElement(By.xpath("//option[. = 'pubblico']")).click();
    }
    driver.findElement(By.id("show_severity_filter")).click();
    {
      WebElement element = driver.findElement(By.id("show_severity_filter"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.name("severity[]")).click();
    {
      WebElement dropdown = driver.findElement(By.name("severity[]"));
      dropdown.findElement(By.xpath("//option[. = 'maggiore']")).click();
    }
    driver.findElement(By.cssSelector(".no-float")).click();
    driver.findElement(By.name("save_query_button")).click();
    driver.findElement(By.name("query_name")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".checkbox:nth-child(7) .lbl")).click();
    driver.findElement(By.name("query_name")).click();
    driver.findElement(By.name("query_name")).sendKeys("Filtro di prova");
    driver.findElement(By.cssSelector(".btn:nth-child(9)")).click();
  }
}
