package Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateAccount1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createAccount1() throws InterruptedException {
    driver.get("http://localhost/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    Thread.sleep(1000);
    driver.findElement(By.linkText("Create an Account")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Mario");
    driver.findElement(By.id("lastname")).sendKeys("Rossi");
    driver.findElement(By.id("email_address")).click();
    driver.findElement(By.id("email_address")).sendKeys("prova@prova.com");
    driver.findElement(By.id("password")).sendKeys("Pupazzo1");
    driver.findElement(By.id("password-confirmation")).click();
    driver.findElement(By.id("password-confirmation")).sendKeys("Pupazzo1");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".submit > span")).click();
    Thread.sleep(1000);
    driver.findElement(By.linkText("click here")).click();
  }
}
