package JUnit.MantisBT;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.interactions.Actions;

import java.util.*;

public class CreateUser1Test {
  private  WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;


  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver=driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createUser1() throws InterruptedException {
    driver.get("http://localhost:8989/login_page.php");
    driver.manage().window().setSize(new Dimension(766, 640));
    driver.findElement(By.id("username")).sendKeys("administrator");
    driver.findElement(By.cssSelector(".width-40")).click();
    driver.findElement(By.id("password")).sendKeys("root");
    driver.findElement(By.cssSelector(".width-40")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("menu-toggler")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("li:nth-child(7) .menu-text")).click();
    driver.findElement(By.linkText("Gestione utenti")).click();
    driver.findElement(By.xpath("//button[@type=\'submit\']")).click();
    driver.findElement(By.id("user-username")).click();
    driver.findElement(By.id("user-username")).sendKeys("asda");
    driver.findElement(By.id("user-realname")).click();
    driver.findElement(By.id("user-realname")).sendKeys("adsa");
    driver.findElement(By.id("email-field")).click();
    driver.findElement(By.id("email-field")).sendKeys("asdasd");
    driver.findElement(By.id("user-access-level")).click();
    {
      WebElement dropdown = driver.findElement(By.id("user-access-level"));
      dropdown.findElement(By.xpath("//option[. = 'aggiornatore']")).click();
    }
    driver.findElement(By.cssSelector("tr:nth-child(6) .lbl")).click();
    driver.findElement(By.cssSelector(".btn-white")).click();



    driver.findElement(By.xpath("//div[@id=\'main-container\']/div[2]/div[2]/div/div/div[2]/p")).click();
    driver.findElement(By.xpath("//div[@id=\'main-container\']/div[2]/div[2]/div/div/div[2]/div")).click();
    driver.findElement(By.xpath("//div[@id=\'main-container\']/div[5]/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'main-container\']/div[5]/div/div/div/address/strong")).click();
    driver.findElement(By.xpath("//div[@id=\'main-container\']/div[5]/div/div/div/address/small")).click();
    driver.findElement(By.xpath("//div[@id=\'main-container\']/div[5]/div/div/div/address/small[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//img[@alt=\'Powered by Mantis Bug Tracker: a free and open source web based bug tracking system.\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'breadcrumbs\']/ul/li/i")).click();
    driver.findElement(By.xpath("//button[@id=\'menu-toggler\']")).click();
    driver.findElement(By.xpath("//button[@id=\'menu-toggler\']")).click();
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'menu-toggler\']"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
  }
}
