package JUnit.Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class CreateCheckout1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public CreateCheckout1Test(WebDriver driver) {
    this.driver = driver;
  }

  @Before
  public void setUp() {
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createCheckout1() throws InterruptedException {
    driver.get("http://localhost/");
    driver.manage().window().setSize(new Dimension(945,1020));
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".ui-menu.ui-widget.ui-widget-content.ui-corner-all")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#ui-id-3 > span")).click();
    Thread.sleep(1000);
    {
      WebElement element = driver.findElement(By.linkText("Frutta"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    Thread.sleep(1000);
    {
      WebElement element = driver.findElement(By.cssSelector(".price-box"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".tocart > span")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".tocart > span")).click();
    Thread.sleep(1000);
    driver.findElement(By.linkText("shopping cart")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".checkout > span")).click();
  }
}
