package JUnit.Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class CreateOrder1Test {
  private WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;


  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void createOrder1() throws InterruptedException {
    driver.get("http://localhost/admin");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("user");
    driver.findElement(By.id("login")).sendKeys("bitnami1");
    driver.findElement(By.cssSelector(".action-login")).click();
    driver.findElement(By.cssSelector("#menu-magento-sales-sales > a")).click();
    Thread.sleep(1000);
    driver.findElement(By.linkText("Orders")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector("#add > span")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".even > .col-phone")).click();
    Thread.sleep(1000);
    js.executeScript("window.scrollBy(0,600)", "");
    Thread.sleep(2000);
    driver.findElement(By.xpath("//label[contains(.,\'Save in address book\')]")).click();
    Thread.sleep(2000);
    js.executeScript("window.scrollBy(0,600)", "");
    driver.findElement(By.xpath("//div[3]/button/span")).click();






    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
    driver.findElement(By.xpath("//div[3]/button/span")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_prefix\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_firstname\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_middlename\']")).click();
    driver.findElement(By.xpath("//input[@id=\'order-billing_address_lastname\']")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_compared\']/div/h5")).click();
    driver.findElement(By.xpath("//div[@id=\'sidebar_data_pviewed\']/div/h5")).click();
  }
}
