package JUnit.Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class CreateAccount1Test {
  private  WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  public CreateAccount1Test(WebDriver driver) {
    this.driver = driver;
  }

  @Before
  public void setUp() {
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {

    driver.quit();
  }
  @Test
  public void createAccount1() throws InterruptedException {
    driver.get("http://localhost/");
    driver.manage().window().setSize(new Dimension(945, 1020));
    Thread.sleep(1000);
    driver.findElement(By.linkText("Create an Account")).click();
    Thread.sleep(1000);
    driver.findElement(By.id("firstname")).click();
    driver.findElement(By.id("firstname")).sendKeys("Mario");
    driver.findElement(By.id("lastname")).sendKeys("Rossi");
    driver.findElement(By.id("email_address")).click();
    driver.findElement(By.id("email_address")).sendKeys("prova@prova.com");
    driver.findElement(By.id("password")).sendKeys("Pupazzo1");
    driver.findElement(By.id("password-confirmation")).click();
    driver.findElement(By.id("password-confirmation")).sendKeys("Pupazzo1");
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".submit > span")).click();
    Thread.sleep(1000);
    driver.findElement(By.linkText("click here")).click();
  }
}
