package JUnit.Magento;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import java.util.*;

public class ReadPrivacy1Test {
  private WebDriver driver=new ChromeDriver();
  private Map<String, Object> vars=new HashMap<String, Object>();
  JavascriptExecutor js= (JavascriptExecutor) driver;


  public void setUp(WebDriver driver) {
    this.driver.quit();
    this.driver = driver;
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void readPrivacy1() throws InterruptedException {
    driver.get("http://localhost/admin");
    driver.manage().window().setSize(new Dimension(945, 1020));
    driver.findElement(By.id("username")).sendKeys("user");
    driver.findElement(By.id("login")).sendKeys("bitnami1");
    driver.findElement(By.id("login")).sendKeys(Keys.ENTER);
    Thread.sleep(2000);
    driver.findElement(By.xpath("//body[@id=\'html-body\']/div[2]/header/div/div/h1")).click();
    driver.findElement(By.xpath("//main[@id=\'anchor-content\']/div")).click();
    driver.findElement(By.xpath("//div[@id=\'container\']/section/div/header")).click();
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div[2]/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div/div/div")).click();
    driver.findElement(By.xpath("//div[@id=\'container\']/div/div[2]/div[2]/div")).click();
    driver.findElement(By.cssSelector("#menu-magento-marketplace-partners > a")).click();
    Thread.sleep(2000);
    driver.findElement(By.cssSelector(".page-footer")).click();
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.xpath("//a[contains(@href, \'https://magento.com/sites/default/files/REVISED-MAGENTO-PRIVACY-POLICY.pdf\')]")).click();
    vars.put("win5173", waitForWindow(2000));
  }
}
